import i18n from "i18next";
import { initReactI18next } from "react-i18next";

const resources = {
  en: {
    MEC_VERSION: "Version v1.0",
    MEC_HELLO: "Hello",
    MEC_LANGUAGE_CHANGED: "Change language",
    MEC_LANGUAGE_HAS_BEEN_CHANGED: "Language has been changed.",
    MEC_ACCOUNT_INFORMATION: "Account Information",
    MEC_CHANGE_PASSWORD: "Change Password",
    MEC_LOGOUT: "Log Out",
    MEC_NOTIFICATION: "Notifications",
    MEC_GENERAL: "General",
    MEC_OVERVIEW: "Overview",
    MEC_TOTAL_SALE: "Total sale",
    MEC_TOTAL_ORDERS: "Total orders",
    MEC_TOTAL_EARNINGS: "Total earnings",
    MEC_REVENUE: "Revenue",
    MEC_ORDERS_ANALYTICS: "Orders analytics",
    MEC_MOST_ORDERS: "Most orders",
    MEC_CUSTOMER: "Customer",
    MEC_ADD_CUSTOMER: "Add customer",
    MEC_LIST_OF_CUSTOMERS: "List of customers",
    MEC_SHOP: "Shop",
    MEC_ADD_SHOP: "Add shop",
    MEC_LIST_OF_STORES: "List of stores",
    MEC_CATEGORY: "Category",
    MEC_PRODUCT: "Product",
    MEC_LIST_OF_PRODUCTS: "List of products",
    MEC_ADD_PRODUCT: "Add product",
    MEC_ORDER: "Order",
    MEC_LIST_OF_ORDERS: "List of orders",
    MEC_ADD_ORDER: "Add order",
    MEC_NEWS: "News",
    MEC_CREATE_NEWS: "Add news",
    MEC_LIST_OF_NEWS: "List of news",
    MEC_NEWS_CATEGORY: "New Category",
    MEC_VEHICLE: "Vehicle",
    MEC_ADD_VEHICLE: "Add vehicle",
    MEC_LIST_OF_VEHICLES: "List of vehicles",
    MEC_PROMOTION: "Coupon",
    MEC_ADD_PROMOTION: "Add promotion",
    MEC_LIST_OF_PROMOTIONS: "List of promotions",
    MEC_MARKETING: "Marketing",
    MEC_STATISTICS: "Statistical",
    MEC_ADVERTISEMENT: "Advertisement",
    MEC_ADD_ADVERTISEMENT: "Add advertisement",
    MEC_LIST_OF_ADVERTISEMENTS: "List of advertisements",
    MEC_ACCOUNT: "Account",
    MEC_ADD_ACCOUNT: "Add Account",
    MEC_LIST_ACCOUNT: "List of Accounts",
    MEC_ADD_NOTIFICATION_TO_STAFF: "Add notification to staff",
    MEC_EMPLOYEE_NOTIFICATION_LIST: "Employee notification list",
    MEC_SERVICE: "Service",
    MEC_LIST_OF_SERVICE: "List of Services",
    MEC_ADD_SERVICE: "Add Service",
    MEC_CONFIGURATION: "Configuration",
    MEC_GENERAL_CONFIGURATION: "General Configuration",
    MEC_SYSTEM: "System",
    MEC_CACHING: "Caching",
    MEC_LIST_OF_CACHING: "List of Caching",
    MEC_ADD_CACHING: "Add caching",
    MEC_EDIT_CACHING: "Edit caching",
    MEC_SYSTEM_SERVICE: "Service permissions",
    MEC_CREATE_PRODUCT_GROUPS: "Create product groups",
    MEC_LIST_OF_PRODUCT_GROUPS: "List of product groups",
    MEC_ACCESS_HISTORY: "Access history",
    MEC_SYSTEM_PERMISSIONS: "System permissions",
    MEC_SYSTEM_MODULE: "Module",
    MEC_SYSTEM_FEATURE: "Feature",
    MEC_SYSTEM_PERFORMANCE: "Performance",
    MEC_GO_BACK: "Go Back",
    MEC_SAVE: "Save",
    MEC_ADD: "Add",
    MEC_EDIT: "Edit",
    MEC_IMPORT: "Import",
    MEC_IMPORT_FRON_EXCEL: "Import from excel",
    MEC_PROCESS_INFORMATION: "Process Information",
    MEC_MANAGEMENT: "Management",
    MEC_SEND_NOTIFICATION: "Send Notification",
    MEC_CONFIRM: "Confirm",
    MEC_TOTAL: "Total",
    MEC_BUTTON_ENTER_CONTENT: "Enter content",
    MEC_BUTTON_SEARCH: "Search",
    MEC_FROM_DATE: "From date",
    MEC_TO_DATE: "To date",
  },
  vi: {
    MEC_VERSION: "Phiên bản v1.0",
    MEC_HELLO: "Chào",
    MEC_LANGUAGE_CHANGED: "Thay đổi ngôn ngữ",
    MEC_LANGUAGE_HAS_BEEN_CHANGED: "Ngôn ngữ đã được thay đổi.",
    MEC_ACCOUNT_INFORMATION: "Thông tin tài khoản",
    MEC_CHANGE_PASSWORD: "Thay đổi mật khẩu",
    MEC_LOGOUT: "Đăng xuất",
    MEC_NOTIFICATION: "Thông báo",
    MEC_GENERAL: "Chung",
    MEC_OVERVIEW: "Tổng quan",
    MEC_TOTAL_SALE: "Tổng doanh thu bán hàng",
    MEC_TOTAL_ORDERS: "Tổng đơn đặt hàng",
    MEC_TOTAL_EARNINGS: "Tổng thu nhập",
    MEC_REVENUE: "Doanh thu",
    MEC_ORDERS_ANALYTICS: "Phân tích đơn hàng",
    MEC_MOST_ORDERS: "Hình thức bán hàng",
    MEC_CUSTOMER: "Khách hàng",
    MEC_ADD_CUSTOMER: "Thêm khách hàng",
    MEC_LIST_OF_CUSTOMERS: "Danh sách khách hàng",
    MEC_SHOP: "Cửa hàng",
    MEC_ADD_SHOP: "Thêm cửa hàng",
    MEC_LIST_OF_STORES: "Danh sách cửa hàng",
    MEC_CATEGORY: "Danh mục",
    MEC_PRODUCT: "Sản phẩm",
    MEC_LIST_OF_PRODUCTS: "Danh sách sản phẩm",
    MEC_ADD_PRODUCT: "Thêm sản phẩm",
    MEC_ORDER: "Đơn hàng",
    MEC_LIST_OF_ORDERS: "Danh sách đơn hàng",
    MEC_ADD_ORDER: "Thêm đơn hàng",
    MEC_NEWS: "Tin tức",
    MEC_CREATE_NEWS: "Thêm tin",
    MEC_LIST_OF_NEWS: "Danh sách tin tức",
    MEC_NEWS_CATEGORY: "Danh mục tin tức",
    MEC_VEHICLE: "Phương tiện",
    MEC_ADD_VEHICLE: "Thêm phương tiện",
    MEC_LIST_OF_VEHICLES: "Danh sách phương tiện",
    MEC_PROMOTION: "Giảm giá",
    MEC_ADD_PROMOTION: "Thêm khuyến mãi",
    MEC_LIST_OF_PROMOTIONS: "Danh sách khuyến mãi",
    MEC_MARKETING: "Tiếp thị",
    MEC_STATISTICS: "Thống kê báo cáo",
    MEC_ADVERTISEMENT: "Quảng cáo",
    MEC_ADD_ADVERTISEMENT: "Thêm quảng cáo",
    MEC_LIST_OF_ADVERTISEMENTS: "Danh sách quảng cáo",
    MEC_ACCOUNT: "Tài khoản",
    MEC_ADD_ACCOUNT: "Thêm tài khoản",
    MEC_LIST_ACCOUNT: "Danh sách tài khoản",
    MEC_ADD_NOTIFICATION_TO_STAFF: "Thêm thông báo cho nhân viên",
    MEC_EMPLOYEE_NOTIFICATION_LIST: "Danh sách thông báo cho nhân viên",
    MEC_SERVICE: "Dịch vụ",
    MEC_LIST_OF_SERVICE: "Danh sách dịch vụ",
    MEC_ADD_SERVICE: "Thêm dịch vụ",
    MEC_CONFIGURATION: "Cấu hình",
    MEC_GENERAL_CONFIGURATION: "Cấu hình chung",
    MEC_SYSTEM: "Hệ thống",
    MEC_CACHING: "Caching",
    MEC_LIST_OF_CACHING: "Danh sách caching",
    MEC_ADD_CACHING: "Thêm caching",
    MEC_EDIT_CACHING: "Chỉnh sửa caching",
    MEC_SYSTEM_SERVICE: "Phân quyền dịch vụ",
    MEC_CREATE_PRODUCT_GROUPS: "Tạo nhóm sản phẩm mới",
    MEC_LIST_OF_PRODUCT_GROUPS: "Danh sách các nhóm sản phẩm",
    MEC_ACCESS_HISTORY: "Lịch sử truy cập",
    MEC_SYSTEM_PERMISSIONS: "Phân quyền hệ thống",
    MEC_SYSTEM_MODULE: "Module",
    MEC_SYSTEM_FEATURE: "Chức năng",
    MEC_SYSTEM_PERFORMANCE: "Hiệu năng",
    MEC_GO_BACK: "Quay lại",
    MEC_ADD: "Thêm",
    MEC_EDIT: "Chỉnh sửa",
    MEC_IMPORT: "Nhập dữ liệu",
    MEC_IMPORT_FRON_EXCEL: "Nhập từ excel",
    MEC_PROCESS_INFORMATION: "Xử lý dữ liệu",
    MEC_SAVE: "Lưu",
    MEC_SEND_NOTIFICATION: "Gửi thông báo",
    MEC_CONFIRM: "Xác nhận",
    MEC_TOTAL: "Tổng",
    MEC_BUTTON_ENTER_CONTENT: "Nhập nội dung",
    MEC_BUTTON_SEARCH: "Tìm kiếm",
    MEC_FROM_DATE: "Từ ngày",
    MEC_TO_DATE: "Đến ngày",
  },
};

function formatResources(resources) {
  const formattedResources = {};
  for (const lang in resources) {
    formattedResources[lang] = {
      translation: {},
    };
    for (const key in resources[lang]) {
      formattedResources[lang].translation[key] = resources[lang][key];
    }
  }
  return formattedResources;
}

i18n.use(initReactI18next).init({
  resources: formatResources(resources),
  lng: "vi",
  fallbackLng: "vi",
  interpolation: {
    escapeValue: false,
  },
});
